set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind c new-window -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
