[env]
term = "alacritty-direct"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
startup_mode = "Maximized"

[font]
size = 16

[font.normal]
family = "JetBrainsMono NFM"
